const db = require("../..");

db.User.bulkCreate([
  {
    userAccount: "misterManager",
    userPassword: "password",
    userFirstName: "Mister",
    userLastName: "Manager",
    managerID: 1,
    isManager: 1,
    sundayAvailable: 1,
    mondayAvailable: 1,
    tuesdayAvailable: 1,
    wednesdayAvailable: 1,
    thursdayAvailable: 1,
    fridayAvailable: 1,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "steveGobs",
    userPassword: "password",
    userFirstName: "Steve",
    userLastName: "Gobs",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 1,
    mondayAvailable: 1,
    tuesdayAvailable: 1,
    wednesdayAvailable: 1,
    thursdayAvailable: 1,
    fridayAvailable: 1,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "collinStrive",
    userPassword: "password",
    userFirstName: "Collin",
    userLastName: "Strive",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 1,
    mondayAvailable: 0,
    tuesdayAvailable: 1,
    wednesdayAvailable: 1,
    thursdayAvailable: 1,
    fridayAvailable: 1,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "karitaHyacinthe",
    userPassword: "password",
    userFirstName: "Karita",
    userLastName: "Hyacinthe",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 1,
    tuesdayAvailable: 1,
    wednesdayAvailable: 1,
    thursdayAvailable: 1,
    fridayAvailable: 0,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "erastosStephanie",
    userPassword: "password",
    userFirstName: "Erastos",
    userLastName: "Stephanie",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 1,
    mondayAvailable: 0,
    tuesdayAvailable: 1,
    wednesdayAvailable: 0,
    thursdayAvailable: 1,
    fridayAvailable: 0,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "mayamikoZenobia",
    userPassword: "password",
    userFirstName: "Mayamiko",
    userLastName: "Zenobia",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 1,
    mondayAvailable: 1,
    tuesdayAvailable: 0,
    wednesdayAvailable: 0,
    thursdayAvailable: 0,
    fridayAvailable: 0,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "williamSmith",
    userPassword: "password",
    userFirstName: "William",
    userLastName: "Smith",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 1,
    mondayAvailable: 0,
    tuesdayAvailable: 1,
    wednesdayAvailable: 1,
    thursdayAvailable: 0,
    fridayAvailable: 1,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "bernardAbernathe",
    userPassword: "password",
    userFirstName: "Bernard",
    userLastName: "Abernathe",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 1,
    mondayAvailable: 1,
    tuesdayAvailable: 0,
    wednesdayAvailable: 1,
    thursdayAvailable: 0,
    fridayAvailable: 1,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "raulDelgado",
    userPassword: "password",
    userFirstName: "Raul",
    userLastName: "Delgado",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 1,
    tuesdayAvailable: 0,
    wednesdayAvailable: 1,
    thursdayAvailable: 0,
    fridayAvailable: 0,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "beckyMcguire",
    userPassword: "password",
    userFirstName: "Becky",
    userLastName: "Mcguire",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 1,
    tuesdayAvailable: 0,
    wednesdayAvailable: 1,
    thursdayAvailable: 0,
    fridayAvailable: 1,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "malcolmChapman",
    userPassword: "password",
    userFirstName: "Malcolm",
    userLastName: "Chapman",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 1,
    tuesdayAvailable: 0,
    wednesdayAvailable: 0,
    thursdayAvailable: 0,
    fridayAvailable: 0,
    saturdayAvailable: 0,
    CompanyId: 1
  },
  {
    userAccount: "randalPatterson",
    userPassword: "password",
    userFirstName: "Randal",
    userLastName: "Patterson",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 1,
    tuesdayAvailable: 1,
    wednesdayAvailable: 1,
    thursdayAvailable: 0,
    fridayAvailable: 1,
    saturdayAvailable: 0,
    CompanyId: 1
  },
  {
    userAccount: "joshuaCannon",
    userPassword: "password",
    userFirstName: "Joshua",
    userLastName: "Cannon",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 1,
    mondayAvailable: 1,
    tuesdayAvailable: 0,
    wednesdayAvailable: 1,
    thursdayAvailable: 0,
    fridayAvailable: 0,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "lanaBush",
    userPassword: "password",
    userFirstName: "Lana",
    userLastName: "Bush",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 1,
    tuesdayAvailable: 0,
    wednesdayAvailable: 0,
    thursdayAvailable: 1,
    fridayAvailable: 1,
    saturdayAvailable: 0,
    CompanyId: 1
  },
  {
    userAccount: "joannBates",
    userPassword: "password",
    userFirstName: "Joann",
    userLastName: "Bates",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 1,
    tuesdayAvailable: 1,
    wednesdayAvailable: 1,
    thursdayAvailable: 1,
    fridayAvailable: 0,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "alfredPerry",
    userPassword: "password",
    userFirstName: "Alfred",
    userLastName: "Perry",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 0,
    tuesdayAvailable: 0,
    wednesdayAvailable: 0,
    thursdayAvailable: 0,
    fridayAvailable: 1,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "rogerAlvarez",
    userPassword: "password",
    userFirstName: "Roger",
    userLastName: "Alvarez",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 0,
    tuesdayAvailable: 1,
    wednesdayAvailable: 0,
    thursdayAvailable: 0,
    fridayAvailable: 1,
    saturdayAvailable: 0,
    CompanyId: 1
  },
  {
    userAccount: "idaWillis",
    userPassword: "password",
    userFirstName: "Ida",
    userLastName: "Willis",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 1,
    tuesdayAvailable: 0,
    wednesdayAvailable: 0,
    thursdayAvailable: 1,
    fridayAvailable: 1,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "stephanieHoffman",
    userPassword: "password",
    userFirstName: "Stephanie",
    userLastName: "Hoffman",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 0,
    tuesdayAvailable: 0,
    wednesdayAvailable: 0,
    thursdayAvailable: 0,
    fridayAvailable: 0,
    saturdayAvailable: 0,
    CompanyId: 1
  },
  {
    userAccount: "williamGriffin",
    userPassword: "password",
    userFirstName: "William",
    userLastName: "Griffin",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 1,
    tuesdayAvailable: 1,
    wednesdayAvailable: 0,
    thursdayAvailable: 0,
    fridayAvailable: 1,
    saturdayAvailable: 0,
    CompanyId: 1
  },
  {
    userAccount: "camilleWade",
    userPassword: "password",
    userFirstName: "Camille",
    userLastName: "Wade",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 1,
    mondayAvailable: 1,
    tuesdayAvailable: 0,
    wednesdayAvailable: 1,
    thursdayAvailable: 1,
    fridayAvailable: 1,
    saturdayAvailable: 0,
    CompanyId: 1
  },
  {
    userAccount: "juliaPittman",
    userPassword: "password",
    userFirstName: "Julia",
    userLastName: "Pittman",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 0,
    tuesdayAvailable: 1,
    wednesdayAvailable: 1,
    thursdayAvailable: 0,
    fridayAvailable: 1,
    saturdayAvailable: 0,
    CompanyId: 1
  },
  {
    userAccount: "adaCooper",
    userPassword: "password",
    userFirstName: "Ada",
    userLastName: "Cooper",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 1,
    mondayAvailable: 1,
    tuesdayAvailable: 1,
    wednesdayAvailable: 1,
    thursdayAvailable: 0,
    fridayAvailable: 0,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "keithSummers",
    userPassword: "password",
    userFirstName: "Keith",
    userLastName: "Summers",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 1,
    tuesdayAvailable: 0,
    wednesdayAvailable: 0,
    thursdayAvailable: 1,
    fridayAvailable: 0,
    saturdayAvailable: 1,
    CompanyId: 1
  },
  {
    userAccount: "cathySandoval",
    userPassword: "password",
    userFirstName: "Cathy",
    userLastName: "Sandoval",
    managerID: 1,
    isManager: 0,
    sundayAvailable: 0,
    mondayAvailable: 0,
    tuesdayAvailable: 1,
    wednesdayAvailable: 1,
    thursdayAvailable: 1,
    fridayAvailable: 0,
    saturdayAvailable: 0,
    CompanyId: 1
  }
]);
