[
    {
        "userAccount": "domingoParsons",
        "userPassword": "password",
        "userFirstName": "Domingo",
        "userLastName": "Parsons",
        "managerID": 1,
        "isManager": 1,
        "sundayAvailable": 1,
        "mondayAvailable": 1,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 1,
        "fridayAvailable": 1,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "dianneMclaughlin",
        "userPassword": "password",
        "userFirstName": "Dianne",
        "userLastName": "Mclaughlin",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 1,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 1,
        "fridayAvailable": 1,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "christinaSchwartz",
        "userPassword": "password",
        "userFirstName": "Christina",
        "userLastName": "Schwartz",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 0,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 1,
        "fridayAvailable": 1,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "joanHughes",
        "userPassword": "password",
        "userFirstName": "Joan",
        "userLastName": "Hughes",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 1,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 0,
        "fridayAvailable": 1,
        "saturdayAvailable": 0,
        "CompanyId": 2
    },
    {
        "userAccount": "opalSpencer",
        "userPassword": "password",
        "userFirstName": "Opal",
        "userLastName": "Spencer",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 0,
        "mondayAvailable": 0,
        "tuesdayAvailable": 0,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 0,
        "fridayAvailable": 1,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "shelleyTorres",
        "userPassword": "password",
        "userFirstName": "Shelley",
        "userLastName": "Torres",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 0,
        "mondayAvailable": 0,
        "tuesdayAvailable": 0,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 1,
        "fridayAvailable": 0,
        "saturdayAvailable": 0,
        "CompanyId": 2
    },
    {
        "userAccount": "andrewJacobs",
        "userPassword": "password",
        "userFirstName": "Andrew",
        "userLastName": "Jacobs",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 0,
        "mondayAvailable": 0,
        "tuesdayAvailable": 0,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 1,
        "fridayAvailable": 1,
        "saturdayAvailable": 0,
        "CompanyId": 2
    },
    {
        "userAccount": "jessePorter",
        "userPassword": "password",
        "userFirstName": "Jesse",
        "userLastName": "Porter",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 0,
        "tuesdayAvailable": 0,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 1,
        "fridayAvailable": 1,
        "saturdayAvailable": 0,
        "CompanyId": 2
    },
    {
        "userAccount": "carlBennett",
        "userPassword": "password",
        "userFirstName": "Carl",
        "userLastName": "Bennett",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 0,
        "mondayAvailable": 0,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 0,
        "thursdayAvailable": 1,
        "fridayAvailable": 0,
        "saturdayAvailable": 0,
        "CompanyId": 2
    },
    {
        "userAccount": "manuelPerry",
        "userPassword": "password",
        "userFirstName": "Manuel",
        "userLastName": "Perry",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 1,
        "tuesdayAvailable": 0,
        "wednesdayAvailable": 0,
        "thursdayAvailable": 1,
        "fridayAvailable": 1,
        "saturdayAvailable": 0,
        "CompanyId": 2
    },
    {
        "userAccount": "amosZimmerman",
        "userPassword": "password",
        "userFirstName": "Amos",
        "userLastName": "Zimmerman",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 0,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 0,
        "thursdayAvailable": 0,
        "fridayAvailable": 0,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "patrickMaxwell",
        "userPassword": "password",
        "userFirstName": "Patrick",
        "userLastName": "Maxwell",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 0,
        "mondayAvailable": 1,
        "tuesdayAvailable": 0,
        "wednesdayAvailable": 0,
        "thursdayAvailable": 1,
        "fridayAvailable": 1,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "erikStone",
        "userPassword": "password",
        "userFirstName": "Erik",
        "userLastName": "Stone",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 0,
        "mondayAvailable": 0,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 1,
        "fridayAvailable": 0,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "sammyHammond",
        "userPassword": "password",
        "userFirstName": "Sammy",
        "userLastName": "Hammond",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 0,
        "mondayAvailable": 0,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 0,
        "thursdayAvailable": 0,
        "fridayAvailable": 1,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "patsyWilson",
        "userPassword": "password",
        "userFirstName": "Patsy",
        "userLastName": "Wilson",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 0,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 0,
        "fridayAvailable": 0,
        "saturdayAvailable": 0,
        "CompanyId": 2
    },
    {
        "userAccount": "earlGrant",
        "userPassword": "password",
        "userFirstName": "Earl",
        "userLastName": "Grant",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 0,
        "tuesdayAvailable": 0,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 0,
        "fridayAvailable": 1,
        "saturdayAvailable": 0,
        "CompanyId": 2
    },
    {
        "userAccount": "stacyHogan",
        "userPassword": "password",
        "userFirstName": "Stacy",
        "userLastName": "Hogan",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 0,
        "mondayAvailable": 1,
        "tuesdayAvailable": 0,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 0,
        "fridayAvailable": 0,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "santiagoHolmes",
        "userPassword": "password",
        "userFirstName": "Santiago",
        "userLastName": "Holmes",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 0,
        "mondayAvailable": 1,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 0,
        "fridayAvailable": 0,
        "saturdayAvailable": 0,
        "CompanyId": 2
    },
    {
        "userAccount": "elsaFrench",
        "userPassword": "password",
        "userFirstName": "Elsa",
        "userLastName": "French",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 1,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 1,
        "fridayAvailable": 0,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "vivianKnight",
        "userPassword": "password",
        "userFirstName": "Vivian",
        "userLastName": "Knight",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 1,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 0,
        "thursdayAvailable": 1,
        "fridayAvailable": 0,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "samuelFigueroa",
        "userPassword": "password",
        "userFirstName": "Samuel",
        "userLastName": "Figueroa",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 1,
        "tuesdayAvailable": 0,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 0,
        "fridayAvailable": 1,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "wallaceSherman",
        "userPassword": "password",
        "userFirstName": "Wallace",
        "userLastName": "Sherman",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 1,
        "tuesdayAvailable": 0,
        "wednesdayAvailable": 0,
        "thursdayAvailable": 1,
        "fridayAvailable": 1,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "phillipTurner",
        "userPassword": "password",
        "userFirstName": "Phillip",
        "userLastName": "Turner",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 0,
        "mondayAvailable": 1,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 0,
        "thursdayAvailable": 0,
        "fridayAvailable": 1,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "marshaSalazar",
        "userPassword": "password",
        "userFirstName": "Marsha",
        "userLastName": "Salazar",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 0,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 0,
        "thursdayAvailable": 0,
        "fridayAvailable": 0,
        "saturdayAvailable": 0,
        "CompanyId": 2
    },
    {
        "userAccount": "bryanGardner",
        "userPassword": "password",
        "userFirstName": "Bryan",
        "userLastName": "Gardner",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 0,
        "tuesdayAvailable": 0,
        "wednesdayAvailable": 0,
        "thursdayAvailable": 0,
        "fridayAvailable": 1,
        "saturdayAvailable": 0,
        "CompanyId": 2
    },
    {
        "userAccount": "luciaBoyd",
        "userPassword": "password",
        "userFirstName": "Lucia",
        "userLastName": "Boyd",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 1,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 0,
        "thursdayAvailable": 1,
        "fridayAvailable": 0,
        "saturdayAvailable": 0,
        "CompanyId": 2
    },
    {
        "userAccount": "janieGutierrez",
        "userPassword": "password",
        "userFirstName": "Janie",
        "userLastName": "Gutierrez",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 1,
        "tuesdayAvailable": 0,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 0,
        "fridayAvailable": 1,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "idaJohnson",
        "userPassword": "password",
        "userFirstName": "Ida",
        "userLastName": "Johnson",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 0,
        "mondayAvailable": 1,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 0,
        "fridayAvailable": 0,
        "saturdayAvailable": 0,
        "CompanyId": 2
    },
    {
        "userAccount": "billyHarrington",
        "userPassword": "password",
        "userFirstName": "Billy",
        "userLastName": "Harrington",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 0,
        "tuesdayAvailable": 0,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 1,
        "fridayAvailable": 1,
        "saturdayAvailable": 1,
        "CompanyId": 2
    },
    {
        "userAccount": "ramiroCastillo",
        "userPassword": "password",
        "userFirstName": "Ramiro",
        "userLastName": "Castillo",
        "managerID": 1,
        "isManager": 0,
        "sundayAvailable": 1,
        "mondayAvailable": 1,
        "tuesdayAvailable": 1,
        "wednesdayAvailable": 1,
        "thursdayAvailable": 0,
        "fridayAvailable": 0,
        "saturdayAvailable": 1,
        "CompanyId": 2
    }
]